# pre-commit 1.1.0 is required for `exclude`
# however `minimum_pre_commit_version` itself requires 1.15.0
minimum_pre_commit_version: "1.15.0"


ci:
    autofix_prs: false
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
    - id: check-shebang-scripts-are-executable
    - id: check-executables-have-shebangs
    - id: check-yaml

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
    - id: black-jupyter

-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.9.1]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.11
  hooks:
  - id: ruff
    args: [--fix]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
